### ISSUE TITLE
VectorPolygonsToRaster issue

### ISSUE THREAD

**Issue by mlavy** [giswqs/whitebox#10]
* whitebox version: 0.9.0
* Python version: 3.7.3
* Operating System: Windows 10

### Description
The whitebox tool "VectorPolygonsToRaster" return a different result compare to the Whitebox GAT -win tool "Vector polygons to raster" . The output .tif has gaps!!!

### What I Did

```
from whitebox import WhiteboxTools

# Set up the environment
wbt = WhiteboxTools()
data_dir = "/../whitebox_issue"
wbt.work_dir = (data_dir) 

i_vector = "poly.shp"
fieldZ = "Value"
out_raster = "poly2raster_PYTHON.tif"

wbt.vector_polygons_to_raster(
    i=i_vector,
    output=out_raster,
    field=fieldZ,
    nodata=True,
    cell_size=1,
   # base=None,
   # callback=default_callback
)
```

![Vector Polygons To Raster - GAT-win](https://user-images.githubusercontent.com/53267230/61803395-576efc80-ae32-11e9-8db5-8b1caa936cd1.JPG)

![poly2raster_GAT-win](https://user-images.githubusercontent.com/53267230/61803163-fb0bdd00-ae31-11e9-8678-4761f88f1d06.jpg)
![poly2raster_PYTHON](https://user-images.githubusercontent.com/53267230/61803164-fba47380-ae31-11e9-8be8-1519d139e5d5.jpg)

**Comment by jblindsay** [comment]
@mlavy This is an issue that belongs in the [WhiteboxTools](https://github.com/jblindsay/whitebox-tools) repository, and not this repository. This repo simply holds the Python frontend for the WhiteboxTools project. I would ask that you please open an issue in the WhiteboxTools repository.
